import type { Metadata } from "next";
import Link from "next/link";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service | Fluxknight",
  description: "Terms governing access to and use of Fluxknight services.",
};

const sections = [
  ["1. Acceptance of these Terms", <>By accessing or using Fluxknight's website, platform, AI agents, automations, integrations or related services (the “Services”), you agree to these Terms. If you use the Services on behalf of a business or organisation, you represent that you have authority to bind that organisation to these Terms.</>],
  ["2. Our Services", <>Fluxknight provides AI-enabled customer operations, sales and support automation, workflow automation, integrations and related software and implementation services. Features may include chat, WhatsApp, email, voice, lead management, scheduling, CRM workflows, analytics and integrations with third-party services. Specific deliverables, limits, pricing and support may also be described in an order, proposal, subscription or service agreement.</>],
  ["3. Accounts and access", <>You are responsible for providing accurate account information, maintaining the confidentiality of credentials and restricting access to your account. You are responsible for activity carried out through your account or authorised integrations. Notify us promptly if you reasonably suspect unauthorised access.</>],
  ["4. Customer responsibilities", <>You are responsible for the data, instructions, content, business rules and permissions you provide to Fluxknight; for ensuring you have lawful authority to process and communicate with your customers and leads; and for reviewing automated workflows before relying on them for material business decisions. You must comply with applicable privacy, marketing, telecommunications, consumer-protection and other laws.</>],
  ["5. Acceptable use", <>You may not use the Services to violate law or third-party rights; distribute unlawful, fraudulent, deceptive, abusive or malicious content; send communications without required permission or lawful basis; attempt unauthorised access to systems or data; interfere with service integrity; introduce malware; evade security controls; or use the Services in a way that creates unreasonable risk to Fluxknight, our providers or other users.</>],
  ["6. AI outputs and automation", <>AI-generated responses and automated decisions can be incomplete or inaccurate. You are responsible for deciding where human review is appropriate and for supervising high-impact or sensitive workflows. Fluxknight does not guarantee that AI outputs will always be correct, uninterrupted or suitable for a particular purpose. The Services are not a substitute for professional legal, medical, financial or other regulated advice.</>],
  ["7. Third-party services", <>The Services may connect to third-party platforms such as messaging, telephony, payment, CRM, email, cloud, AI or automation providers. Your use of those services may be governed by separate terms and policies. Fluxknight is not responsible for outages, policy changes, account restrictions or other acts of third-party providers outside our reasonable control.</>],
  ["8. Fees, subscriptions and taxes", <>Paid Services are subject to the prices, billing cycle and payment terms presented at purchase or in the applicable proposal or agreement. Unless otherwise stated, fees are exclusive of applicable taxes. Failure to pay amounts when due may result in suspension or termination. Any refund rights will be governed by the applicable order, proposal, subscription terms and mandatory law.</>],
  ["9. Intellectual property", <>Fluxknight and its licensors retain rights in the Services, software, designs, workflows, documentation, branding and underlying technology. You retain rights in content and business data you provide. You grant Fluxknight the limited rights necessary to host, process, transmit and otherwise use that content to provide, secure and improve the Services and to fulfil your instructions.</>],
  ["10. Confidentiality", <>Where either party receives non-public business, technical or commercial information that is reasonably understood to be confidential, the receiving party will use reasonable care to protect it and use it only for the relationship, except where disclosure is authorised or required by law.</>],
  ["11. Availability and changes", <>We work to keep the Services reliable, but we do not promise uninterrupted or error-free availability. Maintenance, security incidents, third-party failures and other circumstances may affect service. We may modify features to improve, secure or maintain the Services, while seeking to avoid materially reducing contracted functionality without reasonable notice where practicable.</>],
  ["12. Suspension and termination", <>We may suspend or terminate access where reasonably necessary for security, non-payment, unlawful or abusive use, material breach of these Terms, or protection of Fluxknight, our customers or third parties. You may stop using the Services at any time, subject to any applicable subscription, order or service agreement. Provisions that by their nature should survive termination will survive.</>],
  ["13. Disclaimers", <>To the extent permitted by law, the Services are provided on an “as is” and “as available” basis. We disclaim warranties that are not expressly stated in an applicable written agreement, including implied warranties of merchantability, fitness for a particular purpose and non-infringement, to the extent those disclaimers are legally permitted.</>],
  ["14. Limitation of liability", <>To the maximum extent permitted by applicable law, Fluxknight will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages, or for loss of profits, revenue, goodwill, opportunities or data arising from use of the Services. Where liability cannot lawfully be excluded, any limitation will apply only to the extent permitted by law. A separate signed agreement may specify different liability terms for a particular customer.</>],
  ["15. Indemnity", <>To the extent permitted by law, you agree to be responsible for claims arising from your unlawful use of the Services, your content or instructions, or your material breach of these Terms, except to the extent a claim results from Fluxknight's own breach or unlawful conduct.</>],
  ["16. Governing law and disputes", <>Unless a separate written agreement states otherwise, these Terms are governed by the laws of the Federal Republic of Nigeria, without regard to conflict-of-law principles. Before starting formal proceedings, the parties should make reasonable efforts to resolve a dispute through good-faith discussion. Mandatory rights and jurisdictional protections that cannot lawfully be excluded remain unaffected.</>],
  ["17. Changes to these Terms", <>We may update these Terms as our Services or legal obligations change. The current version will be posted on this page with its effective date. Material changes may be communicated through the Services or other reasonable means where appropriate.</>],
];

export default function TermsPage() {
  return <><Navbar /><main style={{minHeight:"100vh",background:"#050607",color:"#f5f7f8",padding:"132px 24px 88px"}}>
    <article style={{maxWidth:860,margin:"0 auto"}}>
      <p style={{color:"#8bf5bd",fontSize:13,fontWeight:700,letterSpacing:"0.14em",textTransform:"uppercase"}}>Legal</p>
      <h1 style={{fontSize:"clamp(40px,7vw,72px)",lineHeight:1,letterSpacing:"-0.045em",margin:"14px 0 18px"}}>Terms of Service</h1>
      <p style={{color:"#a7afb7",fontSize:16,lineHeight:1.7,marginBottom:48}}>Effective: 25 September 2026</p>
      <p style={{fontSize:18,lineHeight:1.8,color:"#d8dde2",marginBottom:42}}>These Terms of Service govern your access to and use of Fluxknight's website and services. Please read them carefully before using the Services.</p>
      {sections.map(([title,body])=><section key={title as string} style={{padding:"28px 0",borderTop:"1px solid rgba(255,255,255,.1)"}}><h2 style={{fontSize:22,margin:"0 0 12px",letterSpacing:"-.02em"}}>{title}</h2><div style={{color:"#b8c0c7",fontSize:16,lineHeight:1.8}}>{body}</div></section>)}
      <section style={{padding:"28px 0",borderTop:"1px solid rgba(255,255,255,.1)"}}><h2 style={{fontSize:22,margin:"0 0 12px"}}>18. Contact</h2><p style={{color:"#b8c0c7",fontSize:16,lineHeight:1.8}}>Questions about these Terms can be sent to <a href="mailto:limitless@fluxknight.space" style={{color:"#8bf5bd"}}>limitless@fluxknight.space</a> or through our <Link href="/contact" style={{color:"#8bf5bd"}}>contact page</Link>.</p></section>
    </article>
  </main><Footer /></>;
}