export type FollowupStep = { id:string; sequence_id:string; position:number; channel:"whatsapp"|"email"|"call"|"telegram"|"task"; delay_value:number; delay_unit:string; title:string|null; message_template:string|null; workflow_id:string|null; enabled:boolean };
export type FollowupSequence = { id:string; organization_id:string; name:string; description:string|null; status:string; created_at:string; updated_at:string };
export type FollowupEnrollment = { id:string; organization_id:string; sequence_id:string; lead_id:string; lead_name:string|null; lead_phone:string|null; status:string; current_step:number; next_run_at:string|null; last_run_at:string|null; n8n_execution_id:string|null; pause_reason:string|null; created_at:string; updated_at:string };
export type FollowupLog = { id:string; enrollment_id:string; sequence_id:string; step_id:string; organization_id:string; lead_id:string; channel:string|null; status:string|null; n8n_execution_id:string|null; scheduled_for:string|null; executed_at:string|null; error_message:string|null; created_at:string };
export type LegacyFollowup = { id:string; organization_id:string; lead_id:string; scheduled_at:string; message_sent:string|null; status:string; sent_at:string|null; stage:number; channel:string; agent_key:string; template_name:string|null };

import { isServerSupabaseConfigured, supabaseServerRequest } from "@/lib/supabase-server-rest";
async function load(org:string,limit=100){return isServerSupabaseConfigured()?supabaseServerRequest<LegacyFollowup[]>(`follow_ups?organization_id=eq.${encodeURIComponent(org)}&select=*&order=scheduled_at.asc&limit=${limit}`):[];}

export async function getFollowupControlSummary(organizationId="limitless-realty"){
 const rows=await load(organizationId),now=Date.now(),active=rows.filter(r=>["pending","scheduled","queued"].includes(r.status)),due=active.filter(r=>new Date(r.scheduled_at).getTime()<=now),upcoming=active.filter(r=>new Date(r.scheduled_at).getTime()>now),overdue=due.filter(r=>now-new Date(r.scheduled_at).getTime()>=86400000),failed=rows.filter(r=>r.status==="failed"),cancelled=rows.filter(r=>r.status==="cancelled");
 return {configured:isServerSupabaseConfigured(),sequences:[] as FollowupSequence[],steps:[] as FollowupStep[],
 enrollments:active.map(r=>({id:r.id,organization_id:r.organization_id,sequence_id:"legacy-follow-up",lead_id:r.lead_id,lead_name:null,lead_phone:null,status:r.status==="pending"?"active":r.status,current_step:r.stage,next_run_at:r.scheduled_at,last_run_at:r.sent_at,n8n_execution_id:null,pause_reason:null,created_at:r.scheduled_at,updated_at:r.sent_at||r.scheduled_at})) as FollowupEnrollment[],
 logs:rows.map(r=>({id:r.id,enrollment_id:r.id,sequence_id:"legacy-follow-up",step_id:String(r.stage),organization_id:r.organization_id,lead_id:r.lead_id,channel:r.channel,status:r.status,n8n_execution_id:null,scheduled_for:r.scheduled_at,executed_at:r.sent_at,error_message:null,created_at:r.scheduled_at})) as FollowupLog[],
 workflows:[] as unknown[],executions:[] as unknown[],statusSummary:{upcoming:upcoming.length,due:due.length-overdue.length,overdue:overdue.length,completed:rows.filter(r=>r.status==="sent").length,failed:failed.length,cancelled:cancelled.length,paused:0,unscheduled:0}};
}
export async function createSequence(input:{organization_id:string;name:string;description?:string;steps:Array<{channel:string;delay_value:number;delay_unit:string;title?:string|null;message_template?:string|null;workflow_id?:string|null;enabled:boolean}>}):Promise<FollowupSequence>{void input;throw new Error("Custom follow-up sequences are not enabled for the legacy Limitless Realty runtime.");}
export async function enrollLeads(input:{organization_id:string;sequence_id:string;start_at?:string;leads:Array<{id:string;name:string;phone:string}>}):Promise<FollowupEnrollment[]>{void input;throw new Error("Manual follow-up enrollment is not enabled for the legacy Limitless Realty runtime.");}
export async function updateEnrollment(id:string,action:string,value?:string){const now=new Date().toISOString(),payload:Record<string,unknown>={};if(action==="cancel")Object.assign(payload,{status:"cancelled"});else if(action==="complete")Object.assign(payload,{status:"sent",sent_at:now});else if(action==="reschedule")Object.assign(payload,{status:"pending",scheduled_at:value});else if(action==="pause")Object.assign(payload,{status:"cancelled"});else if(action==="resume")Object.assign(payload,{status:"pending",scheduled_at:value||now});else if(action==="skip")Object.assign(payload,{status:"sent",sent_at:now});else throw new Error("Unsupported follow-up action.");return supabaseServerRequest<LegacyFollowup[]>(`follow_ups?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(payload)});}
