import type { PlanKey } from "@/lib/industryCatalog";

export type IndustryPricingProfile = {
  slug: string;
  complexity: "Focused" | "Moderate" | "Advanced";
  typicalChannels: string[];
  scopeDrivers: string[];
  planNotes: Partial<Record<PlanKey, string>>;
};

export const industryPricingProfiles: IndustryPricingProfile[] = [
  { slug: "real-estate", complexity: "Advanced", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Lead volume", "Property inventory", "Inspection workflow", "Admins", "Cross-channel follow-up"], planNotes: { basic: "Property Q&A, buyer qualification and handoff.", starter: "Adds enquiry recovery and inspection reminders.", business: "Scales with lead volume, admins, WhatsApp + email and voice usage.", "business-plus": "Adds property, buyer, inspection and deal-stage data infrastructure when available." } },
  { slug: "sales-companies", complexity: "Advanced", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Lead volume", "Qualification depth", "Reps/admins", "Follow-up cadence", "Pipeline integrations"], planNotes: { basic: "Lead qualification and handoff for one primary channel.", starter: "Adds same-channel sales follow-up.", business: "Scales with team access, cross-channel follow-up, reporting and usage.", "business-plus": "Adds prospect, account and opportunity records when released." } },
  { slug: "hotels", complexity: "Moderate", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Booking enquiry volume", "Reservation workflow", "Front-desk users", "Voice usage", "Hotel integrations"], planNotes: { basic: "Guest Q&A, reservation intake and handoff.", starter: "Adds reservation recovery and reminders.", business: "Scales with guest volume, admins, voice and cross-channel follow-up.", "business-plus": "Guest and booking data scope depends on supported hotel integrations." } },
  { slug: "restaurants", complexity: "Advanced", typicalChannels: ["WhatsApp ordering", "Inbound call ordering", "Website", "Email on Business"], scopeDrivers: ["Order volume", "Menu complexity", "Reservation/catering flows", "Voice usage", "POS integrations"], planNotes: { basic: "Menu Q&A plus order, reservation or catering intake.", starter: "Adds recovery and reminders for unfinished customer journeys.", business: "Driven heavily by order volume, voice minutes, admins and multi-channel activity.", "business-plus": "Customer, order and reservation database scope depends on restaurant-system integrations." } },
  { slug: "clinics", complexity: "Advanced", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Appointment volume", "Scheduling workflow", "Admin controls", "Privacy/security", "Clinic integrations"], planNotes: { basic: "Approved non-clinical Q&A, appointment intake and escalation.", starter: "Adds reminders and same-channel administrative follow-up.", business: "Reflects security controls, admin access, voice and workflow complexity.", "business-plus": "Administrative data modules require privacy, consent and compliance scoping." } },
  { slug: "gyms", complexity: "Moderate", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Membership enquiry volume", "Trial flow", "Renewal reminders", "Branches/admins", "Membership integrations"], planNotes: { basic: "Membership Q&A, qualification and trial handoff.", starter: "Adds trial, class and renewal reminders.", business: "Scales with branches, admins and member communication volume.", "business-plus": "Gym Membership System scope depends on member count, branches and integrations." } },
  { slug: "service-businesses", complexity: "Moderate", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Job enquiry volume", "Intake depth", "Quote/booking flow", "Service areas", "Team/admin users"], planNotes: { basic: "Service Q&A, job intake, qualification and handoff.", starter: "Adds quote, booking and site-visit reminders.", business: "Varies with job volume, admins, voice and cross-channel workflows.", "business-plus": "Customer, job, quote and service-history scope is industry-specific." } },
  { slug: "auto-shops", complexity: "Moderate", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Service enquiry volume", "Vehicle intake depth", "Booking/quote flow", "Service reminders", "Workshop integrations"], planNotes: { basic: "Vehicle and service intake with advisor handoff.", starter: "Adds quote, booking and maintenance reminders.", business: "Scales with customer volume, voice usage and admins.", "business-plus": "Vehicle and service-history scope depends on workshop integrations." } },
  { slug: "ecommerce", complexity: "Advanced", typicalChannels: ["Website", "WhatsApp", "Inbound voice where useful", "Email on Business"], scopeDrivers: ["Conversation volume", "Catalog size", "Order support", "Commerce integrations", "Follow-up volume"], planNotes: { basic: "Product Q&A, buying-intent capture and support intake.", starter: "Adds same-channel recovery for unfinished buying journeys.", business: "Strongly affected by conversation volume, catalog complexity and commerce integrations.", "business-plus": "Customer/order context scope depends on the merchant stack." } },
  { slug: "professional-services", complexity: "Moderate", typicalChannels: ["WhatsApp", "Website", "Inbound voice", "Email on Business"], scopeDrivers: ["Prospect volume", "Qualification depth", "Consultation flow", "Proposal/onboarding follow-up", "Admins"], planNotes: { basic: "Service Q&A, discovery intake and professional handoff.", starter: "Adds consultation, proposal and onboarding reminders.", business: "Scales with team size, cross-channel follow-up and workflow depth.", "business-plus": "Client and engagement data scope depends on the firm's structure and integrations." } }
];

export const industryPricingBySlug = Object.fromEntries(industryPricingProfiles.map((profile) => [profile.slug, profile])) as Record<string, IndustryPricingProfile>;
