export const LEO_PUBLIC_KNOWLEDGE = {
  brand: {
    name: "Fluxknight",
    positioning: "AI automation systems built around how a business actually operates.",
    promise: "Connect customer conversations, lead qualification, follow-up, booking, support and business operations through one controlled AI operating layer.",
  },
  services: [
    {
      key: "ai-sales-agents",
      name: "AI Sales Agents",
      summary: "Qualify leads, answer objections, recommend next steps and move opportunities into the sales pipeline.",
    },
    {
      key: "customer-support",
      name: "Customer Support",
      summary: "Resolve routine questions quickly and route sensitive or unusual requests to the correct human.",
    },
    {
      key: "voice-automation",
      name: "Voice Automation",
      summary: "Handle inbound and outbound conversations for qualification, booking, reminders and follow-up.",
    },
    {
      key: "workflow-intelligence",
      name: "Workflow Intelligence",
      summary: "Coordinate business processes through auditable automations, shared data and controlled human escalation.",
    },
    {
      key: "lead-generation",
      name: "Lead Generation",
      summary: "Collect, enrich, segment and route high-intent leads into one controlled system.",
    },
    {
      key: "customer-management",
      name: "Customer Management Automation",
      summary: "Keep customer details, conversations, follow-ups, sales stages and reporting organized in one shared system.",
    },
  ],
  industries: [
    "Hotels",
    "Restaurants",
    "Clinics",
    "Sales Companies",
    "Real Estate",
    "Gyms",
    "Services",
    "Auto Shops",
    "E-commerce",
    "Professional Services",
  ],
  plans: [
    {
      key: "whatsapp-ai-starter",
      name: "WhatsApp AI Starter",
      firstMonth: "₦100,000",
      ongoing: "₦50,000/month",
      bestFor: "Businesses that mainly need enquiry handling, qualification, customer detail capture and follow-up on WhatsApp.",
      includes: [
        "24/7 WhatsApp AI receptionist",
        "Approved FAQ responses",
        "Lead qualification",
        "Customer detail capture",
        "Automated follow-up",
        "Human handoff",
        "Basic dashboard access",
      ],
    },
    {
      key: "ai-call-receptionist",
      name: "AI Call Receptionist",
      firstMonth: "₦200,000",
      ongoing: "₦100,000/month",
      bestFor: "Businesses that need an inbound AI call agent to answer, qualify and route callers.",
      includes: [
        "24/7 inbound AI calls",
        "Approved FAQ responses",
        "Caller qualification",
        "Customer detail capture",
        "Appointment booking where configured",
        "Human escalation",
        "Call summaries",
        "Dashboard lead capture",
      ],
    },
    {
      key: "ai-front-desk-suite",
      name: "AI Front Desk Suite",
      firstMonth: "₦400,000",
      ongoing: "₦250,000/month",
      bestFor: "Businesses that want a connected customer front desk across WhatsApp, inbound calls and email.",
      includes: [
        "WhatsApp AI",
        "Inbound AI call agent",
        "Email automation",
        "Lead qualification",
        "Automated follow-up",
        "Customer detail capture",
        "Booking support",
        "Human handoff",
        "Shared dashboard",
        "Basic reporting",
      ],
    },
    {
      key: "custom-ai-operations",
      name: "Custom AI Operations",
      firstMonth: "Custom",
      ongoing: "Custom",
      bestFor: "Organizations that need multiple agents, departments, branches, advanced workflows or custom integrations.",
      includes: [
        "Multiple AI agents",
        "Multiple departments or branches",
        "Advanced workflow automation",
        "Voice, WhatsApp and email",
        "Custom integrations",
        "Customer-management automation",
        "Advanced analytics",
        "Workflow monitoring",
        "Organization-wide automation",
        "Managed deployment and support",
      ],
    },
  ],
  qualificationQuestions: [
    "What industry is the business in?",
    "What does the business mainly sell or provide?",
    "Which customer channels matter most: WhatsApp, phone, website, email or another channel?",
    "Roughly how many enquiries or customer conversations arrive in a normal month?",
    "What is the biggest operational pain point: slow response, qualification, follow-up, booking, support, lead generation or something else?",
    "How many staff currently handle those enquiries or processes?",
    "Which outcome matters most over the next 90 days?",
  ],
  publicRules: [
    "Do not promise a custom integration, deployment timeline or feature that has not been scoped.",
    "Do not expose internal implementation tools, credentials, infrastructure or private client information.",
    "Recommend the smallest suitable plan first, then explain when a larger plan becomes justified.",
  ],
} as const;
