"use client";
import {FormEvent,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import type {AiModelCatalogItem,OrganizationModelAssignment,OrganizationOption} from "@/lib/ai-model-control";
import styles from "../PlatformControl.module.css";

type Props={models:AiModelCatalogItem[];assignments:OrganizationModelAssignment[];organizations:OrganizationOption[]};
export default function AiModelControl({models,assignments,organizations}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[provider,setProvider]=useState("");const[modelKey,setModelKey]=useState("");const[displayName,setDisplayName]=useState("");const[organizationId,setOrganizationId]=useState(organizations[0]?.id||"");const[modelId,setModelId]=useState(models.find(m=>m.status==="active")?.id||"");
 const activeModels=useMemo(()=>models.filter(m=>m.status==="active"),[models]);const assignmentMap=useMemo(()=>new Map(assignments.map(i=>[i.organization_id,i.model_id])),[assignments]);const modelMap=useMemo(()=>new Map(models.map(i=>[i.id,i])),[models]);
 async function submit(payload:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/api/admin/ai-models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to update model controls.");setMessage("Saved.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Unable to update model controls.")}finally{setBusy(false)}}
 async function createModel(event:FormEvent){event.preventDefault();await submit({action:"create_model",provider,modelKey,displayName});setProvider("");setModelKey("");setDisplayName("")}
 async function assignModel(event:FormEvent){event.preventDefault();await submit({action:"assign_model",organizationId,modelId})}
 return <div className={styles.sectionStack}>
  <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Organization assignments</h2><p>Assign one approved active model to an organization.</p></div><span className={`${styles.status} ${styles.good}`}>Platform controlled</span></div><form onSubmit={assignModel} className={`${styles.formGrid} ${styles.formGridTwo}`}><label><span>Organization</span><select value={organizationId} onChange={e=>setOrganizationId(e.target.value)} required>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Approved model</span><select value={modelId} onChange={e=>setModelId(e.target.value)} required><option value="">Select an active model</option>{activeModels.map(m=><option key={m.id} value={m.id}>{m.display_name} · {m.provider}</option>)}</select></label><button className={styles.primaryButton} type="submit" disabled={busy||!activeModels.length||!organizations.length}>Assign model</button></form>{message?<p className={styles.note}>{message}</p>:null}</section>
  <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Current organization models</h2><p>Assignments are shown against the current registry.</p></div></div><div className={styles.list}>{organizations.map(o=>{const assigned=modelMap.get(assignmentMap.get(o.id)||"");return <div className={styles.row} key={o.id}><div className={styles.rowMain}><strong>{o.name}</strong><span>{o.slug} · {o.status}</span></div><em className={`${styles.status} ${assigned?styles.good:styles.warn}`}>{assigned?`${assigned.display_name} · ${assigned.provider}`:"Not assigned"}</em></div>})}{!organizations.length?<p className={styles.empty}>No organizations exist yet.</p>:null}</div></section>
  <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Register model</h2><p>Add only models Fluxknight can actually operate.</p></div></div><form onSubmit={createModel} className={styles.formGrid}><label><span>Provider</span><input value={provider} onChange={e=>setProvider(e.target.value)} placeholder="openai" required/></label><label><span>Model key</span><input value={modelKey} onChange={e=>setModelKey(e.target.value)} placeholder="Exact provider model ID" required/></label><label><span>Display name</span><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Internal display name" required/></label><button className={styles.secondaryButton} type="submit" disabled={busy}>Register model</button></form></section></div>
  <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Model registry</h2><p>Disabled models remain recorded but cannot be newly assigned.</p></div></div><div className={styles.list}>{models.map(m=><div className={styles.row} key={m.id}><div className={styles.rowMain}><strong>{m.display_name}</strong><span>{m.provider} · {m.model_key}</span></div><button className={styles.secondaryButton} type="button" disabled={busy} onClick={()=>submit({action:"set_status",modelId:m.id,status:m.status==="active"?"disabled":"active"})}>{m.status==="active"?"Disable":"Enable"}</button></div>)}{!models.length?<p className={styles.empty}>No models registered.</p>:null}</div></section>
 </div>
}
