create index if not exists gencouv_email_messages_inbox_idx on public.gencouv_email_messages (organization_id, direction, created_at desc);
create index if not exists gencouv_email_messages_recipient_idx on public.gencouv_email_messages (organization_id, recipient_email, created_at desc);
create index if not exists gencouv_email_suppression_email_idx on public.gencouv_suppression_list (organization_id, normalized_email);
create index if not exists gencouv_campaign_enrollments_email_idx on public.gencouv_campaign_enrollments (organization_id, normalized_email);

alter table public.gencouv_email_messages enable row level security;
alter table public.gencouv_email_events enable row level security;
alter table public.gencouv_email_sequences enable row level security;
alter table public.gencouv_email_sequence_steps enable row level security;
alter table public.gencouv_campaign_enrollments enable row level security;
alter table public.gencouv_suppression_list enable row level security;
alter table public.gencouv_campaign_settings enable row level security;

create policy gencouv_email_messages_admin on public.gencouv_email_messages for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_messages.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_messages.organization_id and m.user_id = auth.uid() and m.status = 'active'));
create policy gencouv_email_events_admin on public.gencouv_email_events for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_events.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_events.organization_id and m.user_id = auth.uid() and m.status = 'active'));
create policy gencouv_email_sequences_admin on public.gencouv_email_sequences for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_sequences.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_email_sequences.organization_id and m.user_id = auth.uid() and m.status = 'active'));
create policy gencouv_email_steps_admin on public.gencouv_email_sequence_steps for all to authenticated using (exists (select 1 from public.gencouv_email_sequences s join public.organization_memberships m on m.organization_id=s.organization_id where s.id = gencouv_email_sequence_steps.sequence_id and m.user_id=auth.uid() and m.status='active')) with check (exists (select 1 from public.gencouv_email_sequences s join public.organization_memberships m on m.organization_id=s.organization_id where s.id = gencouv_email_sequence_steps.sequence_id and m.user_id=auth.uid() and m.status='active'));
create policy gencouv_campaign_enrollments_admin on public.gencouv_campaign_enrollments for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_campaign_enrollments.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_campaign_enrollments.organization_id and m.user_id = auth.uid() and m.status = 'active'));
create policy gencouv_suppression_admin on public.gencouv_suppression_list for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_suppression_list.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_suppression_list.organization_id and m.user_id = auth.uid() and m.status = 'active'));
create policy gencouv_campaign_settings_admin on public.gencouv_campaign_settings for all to authenticated using (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_campaign_settings.organization_id and m.user_id = auth.uid() and m.status = 'active')) with check (exists (select 1 from public.organization_memberships m where m.organization_id = gencouv_campaign_settings.organization_id and m.user_id = auth.uid() and m.status = 'active'));
