create extension if not exists pgcrypto;
create table if not exists public.runtime_context_snapshots (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,execution_id uuid not null,agent_id uuid not null,conversation_id uuid,prompt_version integer,compiled_prompt text not null,memory_snapshot jsonb not null default '[]'::jsonb,knowledge_snapshot jsonb not null default '[]'::jsonb,tool_snapshot jsonb not null default '[]'::jsonb,policy_snapshot jsonb not null default '{}'::jsonb,checksum text not null,created_at timestamptz not null default now(),unique (organization_id, execution_id),foreign key (organization_id, execution_id) references public.runtime_executions(organization_id, id) on delete cascade,foreign key (organization_id, agent_id) references public.agents(organization_id, id) on delete cascade,foreign key (organization_id, conversation_id) references public.agent_conversations(organization_id, id) on delete set null);
create table if not exists public.runtime_retrieval_results (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,execution_id uuid not null,source_type text not null check (source_type in ('memory','knowledge')),source_id uuid,rank integer not null,score numeric,excerpt text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key (organization_id, execution_id) references public.runtime_executions(organization_id, id) on delete cascade);
create table if not exists public.runtime_policy_decisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,execution_id uuid not null,decision_key text not null,outcome text not null check (outcome in ('allow','deny','approval_required','limit')),reason text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key (organization_id, execution_id) references public.runtime_executions(organization_id, id) on delete cascade);
create table if not exists public.runtime_model_requests (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,execution_id uuid not null,provider_assignment_id uuid,status text not null default 'prepared' check (status in ('prepared','sent','streaming','succeeded','failed','cancelled')),request_payload jsonb not null default '{}'::jsonb,response_payload jsonb,input_tokens integer,output_tokens integer,latency_ms integer,error_message text,created_at timestamptz not null default now(),completed_at timestamptz,foreign key (organization_id, execution_id) references public.runtime_executions(organization_id, id) on delete cascade);
create table if not exists public.runtime_progress_events (id bigserial primary key,organization_id uuid not null references public.organizations(id) on delete cascade,execution_id uuid not null,event_type text not null,message text,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key (organization_id, execution_id) references public.runtime_executions(organization_id, id) on delete cascade);
create index if not exists idx_runtime_retrieval_execution on public.runtime_retrieval_results(organization_id, execution_id, source_type, rank); create index if not exists idx_runtime_policy_execution on public.runtime_policy_decisions(organization_id, execution_id, created_at); create index if not exists idx_runtime_progress_execution on public.runtime_progress_events(organization_id, execution_id, id);
alter table public.runtime_context_snapshots enable row level security; alter table public.runtime_retrieval_results enable row level security; alter table public.runtime_policy_decisions enable row level security; alter table public.runtime_model_requests enable row level security; alter table public.runtime_progress_events enable row level security;
create policy runtime_context_tenant on public.runtime_context_snapshots for select to authenticated using (public.is_organization_member(organization_id)); create policy runtime_retrieval_tenant on public.runtime_retrieval_results for select to authenticated using (public.is_organization_member(organization_id)); create policy runtime_policy_tenant on public.runtime_policy_decisions for select to authenticated using (public.is_organization_member(organization_id)); create policy runtime_progress_tenant on public.runtime_progress_events for select to authenticated using (public.is_organization_member(organization_id)); revoke all on public.runtime_model_requests from anon, authenticated;
