create table if not exists public.gencouv_telegram_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  conversation_started_at timestamptz not null default now(),
  source_cohort text,
  source_campaign text,
  note text,
  recorded_by text default 'dashboard'
);

alter table public.gencouv_telegram_conversations enable row level security;

create index if not exists gencouv_telegram_conversations_started_at_idx
  on public.gencouv_telegram_conversations (conversation_started_at desc);
create index if not exists gencouv_telegram_conversations_source_cohort_idx
  on public.gencouv_telegram_conversations (source_cohort);
