"use client";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageSquareText, Mic, Network, Rocket } from "lucide-react";
const plans=[
{icon:MessageSquareText,name:"WhatsApp AI Starter",first:"₦100,000",ongoing:"₦50,000/month",tag:"One focused AI receptionist for WhatsApp.",features:["24/7 WhatsApp AI receptionist","Answers approved customer questions","Lead qualification","Customer detail capture","Automated follow-up","Human handoff when needed","Basic dashboard access"]},
{icon:Mic,name:"AI Call Receptionist",first:"₦200,000",ongoing:"₦100,000/month",tag:"An inbound AI receptionist that never leaves the phone unattended.",features:["24/7 inbound AI call answering","Answers approved FAQs","Caller qualification","Customer detail capture","Appointment booking where configured","Human transfer or escalation","Call summaries","Leads saved to dashboard"]},
{icon:Network,name:"AI Front Desk Suite",first:"₦400,000",ongoing:"₦250,000/month",tag:"WhatsApp, inbound calls and email working as one customer front desk.",features:["WhatsApp AI","Inbound AI call agent","Email automation","Lead qualification","Automated follow-up","Customer detail capture","Booking support","Human handoff","Shared dashboard","Basic reporting"],featured:true},
{icon:Rocket,name:"Custom AI Operations",first:"Custom",ongoing:"Custom",tag:"Organization-wide automation built around your actual operations.",features:["Multiple AI agents","Multiple departments and branches","Advanced workflows","Voice, WhatsApp and email channels","Custom business integrations","Customer-management automation","Reporting and analytics","Workflow monitoring","Managed organization-wide automation"]}
];
function Fade({children,delay=0}:{children:React.ReactNode;delay?:number}){return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.5,delay}}>{children}</motion.div>}
export default function PricingClient(){return <main className="quantix-home"><section className="brand-section" style={{paddingTop:"9rem"}}><div className="brand-shell"><div className="brand-heading"><span className="brand-eyebrow">Fluxknight Pricing</span><h1 style={{fontSize:"clamp(2.5rem,6vw,5rem)",lineHeight:1}}>Start with the AI your business needs today.</h1><p>Your first month covers installation, configuration, deployment and service. From the second month onward, the consecutive fee keeps the system operating, monitored and supported.</p></div></div></section><section className="brand-section"><div className="brand-shell"><div className="brand-grid">{plans.map(({icon:Icon,name,first,ongoing,tag,features,featured},i)=><Fade key={name} delay={i*.06}><article className={`brand-card ${featured?"pricing-featured":""}`}><span className="brand-icon"><Icon size={21}/></span>{featured&&<span className="brand-eyebrow">Most complete starter</span>}<h2>{name}</h2><p>{tag}</p><div style={{display:"grid",gap:12,margin:"22px 0"}}><div><span style={{fontSize:11,opacity:.65,letterSpacing:".08em"}}>FIRST MONTH · INSTALLATION + SERVICE</span><strong style={{display:"block",fontSize:30,marginTop:4}}>{first}</strong></div><div><span style={{fontSize:11,opacity:.65,letterSpacing:".08em"}}>CONSECUTIVELY</span><strong style={{display:"block",fontSize:20,marginTop:4}}>{ongoing}</strong></div></div><h3>What’s included</h3><div style={{display:"grid",gap:10,margin:"14px 0 24px"}}>{features.map(f=><span key={f} style={{display:"flex",gap:9,alignItems:"flex-start"}}><CheckCircle2 size={17}/>{f}</span>)}</div><Link href="/evaluation">Get started <ArrowRight size={15}/></Link></article></Fade>)}</div><div className="use-case-closing" style={{marginTop:"3rem"}}><h2>Need more than a front desk?</h2><p>Custom AI Operations is scoped around your departments, workflows, integrations and customer journey. We map what should be automated before proposing the system, instead of selling you a pile of features your team will never use.</p><div className="hero-buttons"><Link className="button-primary" href="/evaluation">Book an AI Evaluation <ArrowRight size={17}/></Link><Link className="button-secondary" href="/">Back to Home</Link></div></div><p style={{opacity:.65,marginTop:"2rem",fontSize:13}}>Third-party voice, messaging, email and provider usage may be subject to fair-use limits or additional usage charges depending on volume and provider costs.</p></div></section></main>}
